language: python
python:
  - "3.5.3"
  - "3.6.2"
  - "nightly"

script:
  - pip list
  # Run unit tests and integration tests.
  - python -m unittest discover
  - test/integration_tests.sh
  # Run coverage.
  - |
    if [ "$TRAVIS_PYTHON_VERSION" = "3.5.2" ]; then 
      pip install codecov
      coverage run --source zof -m unittest test/*.py
      test/integration_tests.sh --coverage
      codecov
    fi
  # Run pylint
  - pip install pylint
  - pylint --version
  - pylint zof || echo "pylint issues detected!"
  # pylint zof
  # Create source package.
  - python setup.py sdist
  # Run unit tests again from source package.
  - cd dist ; tar xvfz zof-*.tar.gz ; cd zof-* ; python setup.py test

before_install:
  # Install oftr from launchpad.
  - sudo add-apt-repository ppa:byllyfish/oftr -y
  - sudo apt-get update -qq
  - sudo apt-get install oftr -y
  - oftr version

# Per https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: trusty
