language: python
python:
  - "3.5.2"
# - "nightly"

install:
#  - pip3 install codecov pyyaml
  - pip3 install pyyaml
script:
  - python3 -m unittest discover
#  - python3 -m doctest README.adoc
#  - coverage run --source pylibofp -m test
#after_success:
#  - if [ "$TRAVIS_PYTHON_VERSION" != "nightly" ]; then codecov; fi

before_install:
  # Install oftr from launchpad.
  - sudo add-apt-repository ppa:byllyfish/oftr -y
  - sudo apt-get update -qq
  - sudo apt-get install oftr -y
  - oftr version

# Per https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: trusty
