language: python
python:
  - "3.5.2"
# - "nightly"

install:
#  - pip3 install codecov pyyaml
  - pip install pyyaml
script:
  # Run unit tests.
  - python -m unittest discover
  # Create source package.
  - python setup.py sdist
  # Run unit tests from source package.
  - cd dist ; tar xvfz pylibofp-*.tar.gz ; cd pylibofp-* ; python setup.py test

#  - python3 -m doctest README.adoc
#  - coverage run --source pylibofp -m test
#after_success:
#  - if [ "$TRAVIS_PYTHON_VERSION" != "nightly" ]; then codecov; fi

before_install:
  # Install oftr from launchpad.
  - sudo add-apt-repository ppa:byllyfish/oftr -y
  - sudo apt-get update -qq
  - sudo apt-get install oftr -y
  - oftr version

# Per https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: trusty
