language: python
dist: xenial
sudo: true
python:
  - "3.7"
  - "3.8-dev"

before_install:
  # Install oftr from launchpad.
  - sudo add-apt-repository ppa:byllyfish/oftr -y
  - sudo apt-get update -qq
  - sudo apt-get install oftr -y
  - oftr version

install:
    - pip install -U setuptools pip
    - pip install -U -r requirements.txt -r test-requirements.txt

script:
    - ./run_tests.sh
    # Re-run unit tests under builtin loop and uvloop.
    - python -m pytest -s
    - pip install uvloop
    - python -m pytest -s
