language: python
python:
  - "3.5.4"
  - "3.6.3"
  - "nightly"

script:
  - pip list
  # Run unit tests and integration tests.
  - python -m unittest discover
  - test/integration_tests.sh
  # Run coverage.
  - |
    if [ "$TRAVIS_PYTHON_VERSION" = "3.5.4" ]; then 
      pip install codecov
      coverage run --source zof -m unittest test/*.py
      test/integration_tests.sh --coverage
      codecov
    fi
  # Run pylint, flake8, and rstcheck tests
  - pip install pylint flake8 rstcheck
  - pylint --version
  - pylint zof setup.py || echo "pylint issues detected!"
  - flake8 --max-line-length=150 zof test || echo "flake8 issues detected!"
  - rstcheck *.rst doc/sphinx/*.rst || echo "rstcheck issues detected!"
  # Create source package.
  - python setup.py sdist
  # Run unit tests again from source package.
  - cd dist ; tar xvfz zof-*.tar.gz ; cd zof-* ; python setup.py test

before_install:
  # Install oftr from launchpad.
  - sudo add-apt-repository ppa:byllyfish/oftr -y
  - sudo apt-get update -qq
  - sudo apt-get install oftr -y
  - oftr version

# Per https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: trusty
