language: python
python: 3.7
dist: xenial
sudo: true

before_install:
  # Install oftr from launchpad.
  - sudo add-apt-repository ppa:byllyfish/oftr -y
  - sudo apt-get update -qq
  - sudo apt-get install oftr -y
  - oftr version

install:
    - pip install -r test-requirements.txt

script:
    - ./run_tests.sh
